// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using ECommerce.Api.ProductCatalog.Persistence;

namespace ECommerce.Api.ProductCatalog.Migrations
{
    [DbContext(typeof(ContextProduct))]
    [Migration("20200704061638_MigracionSqlServerInicial")]
    partial class MigracionSqlServerInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ECommerce.Api.ProductCatalog.Model.Product", b =>
                {
                  b.Property<Guid?>("Id")
                      .ValueGeneratedOnAdd()
                      .HasColumnType("uniqueidentifier");

                  b.Property<string?>("Description")
                        .HasColumnType("nvarchar(max)");

                  b.Property<DateTime?>("DateCreated")
                        .HasColumnType("datetime2");

                  b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                  b.Property<double>("Price")
                      .HasColumnType("decimal(10,2)");

                  b.HasKey("Id");

                  b.ToTable("Products");
                });
             #pragma warning restore 612, 618
        }
    }
}
